### PR TITLE
Feat/webpack3

### PR DESCRIPTION
**Pull request by dmylian**
Thanks for this starter, decided to help by updating Webpack to the ^3 version and the old configuration file that was created according to the Webpack 1, where now it utilizes slightly different scheme, though the old one is still valid for some time.
Also, there's an optional support for the ESLint with almost basic config and few minor styling updates.

### CODE REVIEW

**Comment by STUkh** [comment]
Good job! Merged.

**Comment by dmylian** [comment]
@STUkh we can also add a [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) in projects with lodash to reduce bundle size overhead. Please inform, if it's worth creating a PR.

**Comment by alex-stepchenkov-neyber** [comment]
@dannymy i think users could use webpack's tree-shaking with native lodash lib, so there's no need to use babel-plugin.

**Comment by STUkh** [comment]
@dannymy i think users could use webpack's tree-shaking with native lodash lib, so there's no need to use babel-plugin.

**Comment by dmylian** [comment]
@STUkh oh, makes sense. But what about [this line](https://github.com/STUkh/generator-angular-webpack-es6/blob/607e4aa1357cf7975d0ec11c4bfe2308c292cb8f/generators/app/templates/_src/_app/_pages/main/main.controller.js#L4), won't it import entire lodash?

**Comment by STUkh** [comment]
@dannymy yes, but i hope that devs know what they do :)

**Pull request merged**
